### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by moaeddy** [cornerpirate/JS2PDFInjector#4]
guess this doesn't work on acrobat 2020.09.20067, tested but "hello world" doesn't popup. what a nice project you put up anyway

**Comment by cornerpirate** [comment]
Hi thanks for the appreciation.

I have just tested this in Windows 10 with version 20.009.20067 (and I ran check for updates and got none). The alert message did popup for me. 

Can you try again please?

**Comment by cornerpirate** [comment]
Closing this because it absolutely worked and there hasn't been an update.
