### ISSUE TITLE
Does not work in Firefox's PDF.js

### ISSUE THREAD

**Issue by sijanec** [cornerpirate/JS2PDFInjector#5]
Too bad.

**Comment by cornerpirate** [comment]
Is there a ticket here?

**Comment by sijanec** [comment]
not at all, I just mentioned that in case someone would try to dive into
the source code thinking it's this program's fault that it doesn't work.

Feel free to close and add a note to README if you think that would
be helpful.

**Comment by cornerpirate** [comment]
Thanks for the additional information.

I direct you to the readme which already states this works in Adobe and pretty much nowhere else:

```When you open the produced PDF with the JavaScript injected in Adobe you should see your code execute. Mileage varys in other viewers and for certain Edge in Windows 10 does not execute.```

I believe that other PDF readers are more sensible and don't have JavaScript :D
