### ISSUE TITLE
Redirect not working

### ISSUE THREAD

**Issue by Mr-P-D** [cornerpirate/JS2PDFInjector#8]
Hello i want to open a pop up in pdf and once they click open i want them to be redirected to my site.

app.alert is working fine but for redirection i tried multiple methods like
location.href
window.location.href
window.location

none of them seem to be working with js2pdfinjector can you suggest one way in which i can achieve this?

**Comment by cornerpirate** [comment]
I believe this is because of changes to the security model of PDF viewers. They stop quite a lot of things by default now.
